### ISSUE TITLE
Byt namn på saker i databasehandler

### ISSUE THREAD

**Issue by KraftKatten** [olssonelina/Programmeringsprinsessorna#64]
PMDn klagar på att det finns massa literaler i databasehandler som heter likadant. Typ JSON, Exception:, \ss+, VARIABLE, params.

Jag kan tycka att det räcker att döpa om varje JSON, VARIABLE och params till vad den ska användas till. Men kanske göra det lite snyggare iaf

- [x] lös det

**Comment by Nightingale1997** [comment]
JSON, VARIABLE och params är alla taggar för loggen/konsollen, och står för kategorier av meddelanden och ska därför inte vara olika.
